#!/bin/sh
set -e

if [ "$1" = "configure" ]
then
  groupadd -r thingsplex || true
  groupadd -r hue-ad || true

  useradd -r -N -M -d / -s /bin/false -g thingsplex hue-ad || true
  if [ ! -f /opt/thingsplex/hue-ad/data/config.json ]; then
		  cp /opt/thingsplex/hue-ad/defaults/config.json /opt/thingsplex/hue-ad/data/config.json || true
	fi
  chown -R hue-ad:thingsplex /var/log/thingsplex/hue-ad/ || true
  chown -R hue-ad:hue-ad /opt/thingsplex/hue-ad/ || true


fi

deb-systemd-helper unmask hue-ad.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled hue-ad.service; then
  systemctl enable hue-ad.service || true
else
  deb-systemd-helper update-state hue-ad.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true

  if [ -n "$2" ]; then
    deb-systemd-invoke try-restart hue-ad.service >/dev/null || true
  else
    deb-systemd-invoke start hue-ad.service >/dev/null || true
  fi
fi