#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask hue-ad.service >/dev/null
  fi
fi

if [ "$1" = "purge" ]; then
  rm -rf /var/lib/futurehome/hue-ad/data
  
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper purge hue-ad.service >/dev/null
    deb-systemd-helper unmask hue-ad.service >/dev/null
  fi
fi